/*
 * Created on 25 oct 2016 ( Time 00:14:37 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.labruzeza.colectividades.modelo;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for 'Configuracion' entity
 * 
 * @author Telosys Tools
 *
 */
public class Configuracion implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : idConfiguracion INT 
    private Integer idconfiguracion;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : nroCaja INT 
    private Integer nrocaja;

    // DB : fecha DATE 
    private Date fecha;

    // DB : tipoCaja VARCHAR 
    private String tipocaja;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdconfiguracion( Integer idconfiguracion ) {
        this.idconfiguracion = idconfiguracion ;
    }

    public Integer getIdconfiguracion() {
        return this.idconfiguracion;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setNrocaja( Integer nrocaja ) {
        this.nrocaja = nrocaja;
    }
    public Integer getNrocaja() {
        return this.nrocaja;
    }

    public void setFecha( Date fecha ) {
        this.fecha = fecha;
    }
    public Date getFecha() {
        return this.fecha;
    }

    public void setTipocaja( String tipocaja ) {
        this.tipocaja = tipocaja;
    }
    public String getTipocaja() {
        return this.tipocaja;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idconfiguracion);
        sb.append("|");
        sb.append(nrocaja);
        sb.append("|");
        sb.append(fecha);
        sb.append("|");
        sb.append(tipocaja);
        return sb.toString(); 
    } 


}
