/*
 * Created on 21 oct 2016 ( Time 11:36:55 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.labruzeza.colectividades.modelo;

import java.io.Serializable;

import java.math.BigDecimal;

/**
 * Java bean for 'Lineadeventa' entity
 * 
 * @author Telosys Tools
 *
 */
public class Lineadeventa implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : idLineaDeVenta INT 
    private Integer idlineadeventa;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : idVenta INT 
    private Integer idventa;

    // DB : idProducto INT 
    private Integer idproducto;

    // DB : precio DECIMAL 
    private BigDecimal precio;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdlineadeventa( Integer idlineadeventa ) {
        this.idlineadeventa = idlineadeventa ;
    }

    public Integer getIdlineadeventa() {
        return this.idlineadeventa;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setIdventa( Integer idventa ) {
        this.idventa = idventa;
    }
    public Integer getIdventa() {
        return this.idventa;
    }

    public void setIdproducto( Integer idproducto ) {
        this.idproducto = idproducto;
    }
    public Integer getIdproducto() {
        return this.idproducto;
    }

    public void setPrecio( BigDecimal precio ) {
        this.precio = precio;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idlineadeventa);
        sb.append("|");
        sb.append(idventa);
        sb.append("|");
        sb.append(idproducto);
        sb.append("|");
        sb.append(precio);
        return sb.toString(); 
    } 


}
