/*
 * Created on 21 oct 2016 ( Time 11:36:55 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.labruzeza.colectividades.modelo;

import java.io.Serializable;

import java.math.BigDecimal;

/**
 * Java bean for 'Producto' entity
 * 
 * @author Telosys Tools
 *
 */
public class Producto implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : idproducto INT 
    private Integer idproducto;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : nombre VARCHAR 
    private String nombre;

    // DB : precio DECIMAL 
    private BigDecimal precio;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdproducto( Integer idproducto ) {
        this.idproducto = idproducto ;
    }

    public Integer getIdproducto() {
        return this.idproducto;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setNombre( String nombre ) {
        this.nombre = nombre;
    }
    public String getNombre() {
        return this.nombre;
    }

    public void setPrecio( BigDecimal precio ) {
        this.precio = precio;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idproducto);
        sb.append("|");
        sb.append(nombre);
        sb.append("|");
        sb.append(precio);
        return sb.toString(); 
    } 


}
