/*
 * Created on 26 oct 2016 ( Time 18:33:34 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.labruzeza.colectividades.modelo;

import java.io.Serializable;

import java.math.BigDecimal;

/**
 * Java bean for 'Vcaja' entity
 * 
 * @author Telosys Tools
 *
 */
public class Vcaja implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : idProducto INT 
    private Integer idproducto;

    // DB : codigo VARCHAR 
    private String codigo;

    // DB : nombre VARCHAR 
    private String nombre;

    // DB : cantidad DECIMAL 
    private BigDecimal cantidad;

    // DB : subtotal DECIMAL 
    private BigDecimal subtotal;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setIdproducto( Integer idproducto ) {
        this.idproducto = idproducto;
    }
    public Integer getIdproducto() {
        return this.idproducto;
    }

    public void setCodigo( String codigo ) {
        this.codigo = codigo;
    }
    public String getCodigo() {
        return this.codigo;
    }

    public void setNombre( String nombre ) {
        this.nombre = nombre;
    }
    public String getNombre() {
        return this.nombre;
    }

    public void setCantidad( BigDecimal cantidad ) {
        this.cantidad = cantidad;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }

    public void setSubtotal( BigDecimal subtotal ) {
        this.subtotal = subtotal;
    }
    public BigDecimal getSubtotal() {
        return this.subtotal;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idproducto);
        sb.append("|");
        sb.append(codigo);
        sb.append("|");
        sb.append(nombre);
        sb.append("|");
        sb.append(cantidad);
        sb.append("|");
        sb.append(subtotal);
        return sb.toString(); 
    } 


}
