/*
 * Created on 26 oct 2016 ( Time 00:08:43 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.labruzeza.colectividades.modelo;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 * Java bean for 'Venta' entity
 * 
 * @author Telosys Tools
 *
 */
public class Venta implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : idventa INT 
    private Integer idventa;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : codigo VARCHAR 
    private String codigo;

    // DB : fecha DATE 
    private Date fecha;

    // DB : codFactura INT 
    private Integer codfactura;
    
    private List<Lineadeventa> listOfLineadeventa;


    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdventa( Integer idventa ) {
        this.idventa = idventa ;
    }

    public Integer getIdventa() {
        return this.idventa;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setCodigo( String codigo ) {
        this.codigo = codigo;
    }
    public String getCodigo() {
        return this.codigo;
    }

    public void setFecha( Date fecha ) {
        this.fecha = fecha;
    }
    public Date getFecha() {
        return this.fecha;
    }

    public void setCodfactura( Integer codfactura ) {
        this.codfactura = codfactura;
    }
    public Integer getCodfactura() {
        return this.codfactura;
    }


    public List<Lineadeventa> getListOfLineadeventa() {
		return listOfLineadeventa;
	}

	public void setListOfLineadeventa(List<Lineadeventa> listOfLineadeventa) {
		this.listOfLineadeventa = listOfLineadeventa;
	}

	//----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idventa);
        sb.append("|");
        sb.append(codigo);
        sb.append("|");
        sb.append(fecha);
        sb.append("|");
        sb.append(codfactura);
        return sb.toString(); 
    } 


}
