version: '3'
services:
  mysql:
    image: mysql:5.7.42
    container_name: mysql_db_caja
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: LabruzezaDB
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  mysql_data:
