/*
 * Created on 25 oct 2016 ( Time 10:26:00 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.labruzeza.colectividades.dao.commons;

import java.sql.SQLException;

import org.junit.Assert;
import org.junit.BeforeClass;
import org.junit.Test;
import org.labruzeza.colectividades.dao.ConfiguracionDAO;
import org.labruzeza.colectividades.dao.impl.jdbc.commons.CreateSchemaDB;
import org.labruzeza.colectividades.modelo.Configuracion;

/**
 * JUnit tests for ConfiguracionDAO
 * 
 * @author Telosys Tools
 *
 */
public class CreateSchemaDBTest {
	@Test
	public void create_squema() {
		CreateSchemaDB createSchemaDB = new CreateSchemaDB();
		createSchemaDB.execute();
	}
}
