/*
 * Created on 21 oct 2016 ( Time 11:36:55 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.labruzeza.colectividades.dao.impl.jdbc.commons;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

import javax.sql.DataSource;

import org.apache.commons.dbcp.BasicDataSource;

/**
 * DataSource provider
 * 
 * @author Telosys Tools
 *
 */
public class DataSourceProvider {
	
	/**
	 * The unique DataSource instance (singleton)
	 */
	private final static DataSource datasource = createDataSource() ;
	
	public static DataSource getDataSource() {
		return datasource;
	}

	private static DataSource createDataSource() {
		Properties env = loadPropertiesFromClassPath(DAOConfiguration.JDBC_PROPERTIES_FILE_NAME);

		BasicDataSource datasource = new BasicDataSource();
		datasource.setDriverClassName(env.getProperty("jdbc.driverClassName"));
		datasource.setUrl(env.getProperty("jdbc.url"));
		datasource.setUsername(env.getProperty("jdbc.username"));
		datasource.setPassword(env.getProperty("jdbc.password"));
		return datasource ;
	}

	private static Properties loadPropertiesFromClassPath(String fileName) {
		Properties properties = new Properties();
		InputStream is = DataSourceProvider.class.getResourceAsStream(fileName) ;
		if ( is != null ) {
			try {
				properties.load( DataSourceProvider.class.getResourceAsStream(fileName) );
			} catch (IOException e) {
				throw new RuntimeException("Cannot load '" + fileName + "'", e);
			}
			return properties ;
		}
		else {
			throw new RuntimeException("Cannot found '" + fileName + "' (InputStream is null)" );
		}
	}
}
