/*
 * Created on 21 oct 2016 ( Time 11:36:54 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.labruzeza.colectividades.dao;

import org.labruzeza.colectividades.modelo.Configuracion;

/**
 * Configuracion DAO interface
 * 
 * @author Telosys Tools
 */
public interface ConfiguracionDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param idconfiguracion
	 * @return the bean found or null if not found 
	 */
	public Configuracion find( Integer idconfiguracion ) ;

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param configuracion
	 * @return true if found, false if not found
	 */
	public boolean load( Configuracion configuracion ) ;
	
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param configuracion
	 * @return the generated value for the auto-incremented column
	 */
	public Integer insert(Configuracion configuracion) ;

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param configuracion
	 * @return
	 */
	public int update(Configuracion configuracion) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @param idconfiguracion
	 * @return
	 */
	public int delete( Integer idconfiguracion ) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param configuracion
	 * @return
	 */
	public int delete( Configuracion configuracion ) ;

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param idconfiguracion
	 * @return
	 */
	public boolean exists( Integer idconfiguracion ) ;

	//----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param configuracion
	 * @return
	 */
	public boolean exists( Configuracion configuracion ) ;

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;

}
