/*
 * Created on 21 oct 2016 ( Time 11:36:55 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.labruzeza.colectividades.dao;

import java.util.List;

import org.labruzeza.colectividades.modelo.Producto;

/**
 * Producto DAO interface
 * 
 * @author Telosys Tools
 */
public interface ProductoDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param idproducto
	 * @return the bean found or null if not found 
	 */
	public Producto find( Integer idproducto ) ;

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param producto
	 * @return true if found, false if not found
	 */
	public boolean load( Producto producto ) ;
	
	public List<Producto> loadAll() ;
	
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param producto
	 * @return the generated value for the auto-incremented column
	 */
	public Integer insert(Producto producto) ;

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param producto
	 * @return
	 */
	public int update(Producto producto) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @param idproducto
	 * @return
	 */
	public int delete( Integer idproducto ) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param producto
	 * @return
	 */
	public int delete( Producto producto ) ;

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param idproducto
	 * @return
	 */
	public boolean exists( Integer idproducto ) ;

	//----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param producto
	 * @return
	 */
	public boolean exists( Producto producto ) ;

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;

}
