/*
 * Created on 21 oct 2016 ( Time 11:36:55 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.labruzeza.colectividades.dao;

import java.util.Date;

import org.labruzeza.colectividades.modelo.Venta;

/**
 * Venta DAO interface
 * 
 * @author Telosys Tools
 */
public interface VentaDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param idventa
	 * @return the bean found or null if not found 
	 */
	public Venta find( Integer idventa ) ;

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param venta
	 * @return true if found, false if not found
	 */
	public boolean load( Venta venta ) ;
	
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param venta
	 * @return the generated value for the auto-incremented column
	 */
	public Integer insert(Venta venta) ;

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param venta
	 * @return
	 */
	public int update(Venta venta) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @param idventa
	 * @return
	 */
	public int delete( Integer idventa ) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param venta
	 * @return
	 */
	public int delete( Venta venta ) ;

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param idventa
	 * @return
	 */
	public boolean exists( Integer idventa ) ;

	//----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param venta
	 * @return
	 */
	public boolean exists( Venta venta ) ;

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;
	
	public long doCountAll( Date date);
	
	public int getUltimo();

}
